source "https://rubygems.org"

# daru is not added in gemspec
gem "daru", git: 'https://github.com/SciRuby/daru.git'
gem 'nyaplot', git: 'https://github.com/sciruby/nyaplot.git'

gemspec :path => '../../'

gem "sinatra"