source "http://rubygems.org"

gem 'nanoc'
# to run nanoc view command
gem 'adsf'

# Fetch gem from git repo
gem "daru", git: 'https://github.com/SciRuby/daru.git'
gem 'nyaplot', git: 'https://github.com/sciruby/nyaplot.git'
gem 'daru-data_tables', git: 'https://github.com/shekharrajak/daru-data_tables.git'
gem 'google_visualr', git: 'https://github.com/winston/google_visualr.git'
gem 'daru-view', git: 'https://github.com/shekharrajak/daru-view.git'

gem 'nokogiri'
